package database

// BuiltinCommands contains rich metadata for standard Linux utilities.
var BuiltinCommands = map[string]CommandDef{
	"tar": {
		Name:        "tar",
		Category:    "Archive",
		Summary:     "Creates, extracts, and lists archive files (.tar, .tar.gz, .tgz, .tar.xz)",
		Description: "Tape Archive utility used to bundle multiple files and directories into a single archive file.",
		DefaultRisk: RiskMedium,
		Flags: map[string]FlagDef{
			"x":         {Short: "-x", Long: "--extract", Description: "Extract files from an archive", Risk: RiskMedium},
			"extract":   {Short: "-x", Long: "--extract", Description: "Extract files from an archive", Risk: RiskMedium},
			"c":         {Short: "-c", Long: "--create", Description: "Create a new archive file", Risk: RiskLow},
			"create":    {Short: "-c", Long: "--create", Description: "Create a new archive file", Risk: RiskLow},
			"z":         {Short: "-z", Long: "--gzip", Description: "Filter archive through gzip compression/decompression (.tar.gz / .tgz)"},
			"gzip":      {Short: "-z", Long: "--gzip", Description: "Filter archive through gzip compression/decompression (.tar.gz / .tgz)"},
			"j":         {Short: "-j", Long: "--bzip2", Description: "Filter archive through bzip2 compression (.tar.bz2)"},
			"bzip2":     {Short: "-j", Long: "--bzip2", Description: "Filter archive through bzip2 compression (.tar.bz2)"},
			"J":         {Short: "-J", Long: "--xz", Description: "Filter archive through xz compression (.tar.xz)"},
			"xz":        {Short: "-J", Long: "--xz", Description: "Filter archive through xz compression (.tar.xz)"},
			"v":         {Short: "-v", Long: "--verbose", Description: "Verbosely list each file being processed in the terminal"},
			"verbose":   {Short: "-v", Long: "--verbose", Description: "Verbosely list each file being processed in the terminal"},
			"f":         {Short: "-f", Long: "--file", TakesValue: true, ValueName: "ARCHIVE", Description: "Specify the archive filename to read or write"},
			"file":      {Short: "-f", Long: "--file", TakesValue: true, ValueName: "ARCHIVE", Description: "Specify the archive filename to read or write"},
			"C":         {Short: "-C", Long: "--directory", TakesValue: true, ValueName: "DIR", Description: "Change to target directory before performing operations"},
			"directory": {Short: "-C", Long: "--directory", TakesValue: true, ValueName: "DIR", Description: "Change to target directory before performing operations"},
			"t":         {Short: "-t", Long: "--list", Description: "List contents of the archive without extracting it", Risk: RiskSafe},
			"list":      {Short: "-t", Long: "--list", Description: "List contents of the archive without extracting it", Risk: RiskSafe},
			"p":         {Short: "-p", Long: "--preserve-permissions", Description: "Preserve original file permissions and attributes"},
			"exclude":   {Long: "--exclude", TakesValue: true, ValueName: "PATTERN", Description: "Exclude files matching the given pattern"},
		},
	},

	"rm": {
		Name:        "rm",
		Category:    "FileOps",
		Summary:     "Permanently removes (deletes) files or directories",
		Description: "Deletes specified files and directory trees. Items deleted with rm bypass Trash and are permanently unrecoverable.",
		DefaultRisk: RiskHigh,
		Flags: map[string]FlagDef{
			"r":                  {Short: "-r", Long: "-R, --recursive", Description: "Recursively remove directories and all of their sub-contents", Risk: RiskCritical},
			"R":                  {Short: "-R", Long: "--recursive", Description: "Recursively remove directories and all of their sub-contents", Risk: RiskCritical},
			"recursive":          {Short: "-r", Long: "--recursive", Description: "Recursively remove directories and all of their sub-contents", Risk: RiskCritical},
			"f":                  {Short: "-f", Long: "--force", Description: "Ignore nonexistent files and never prompt for confirmation", Risk: RiskCritical},
			"force":              {Short: "-f", Long: "--force", Description: "Ignore nonexistent files and never prompt for confirmation", Risk: RiskCritical},
			"i":                  {Short: "-i", Description: "Prompt for confirmation before every single removal", Risk: RiskSafe},
			"I":                  {Short: "-I", Description: "Prompt once before removing more than 3 files or when removing recursively"},
			"v":                  {Short: "-v", Long: "--verbose", Description: "Explain what is being done (display each deleted file)"},
			"verbose":            {Short: "-v", Long: "--verbose", Description: "Explain what is being done (display each deleted file)"},
			"d":                  {Short: "-d", Long: "--dir", Description: "Remove empty directories"},
			"no-preserve-root":   {Long: "--no-preserve-root", Description: "Do not treat '/' specially (EXTREMELY DANGEROUS)", Risk: RiskCritical},
		},
	},

	"cp": {
		Name:        "cp",
		Category:    "FileOps",
		Summary:     "Copies files or directories to a destination",
		Description: "Copies source files or entire directories to specified destination paths.",
		DefaultRisk: RiskLow,
		Flags: map[string]FlagDef{
			"r":         {Short: "-r", Long: "-R, --recursive", Description: "Copy directories recursively with all subdirectories and files"},
			"R":         {Short: "-R", Long: "--recursive", Description: "Copy directories recursively with all subdirectories and files"},
			"recursive": {Short: "-r", Long: "--recursive", Description: "Copy directories recursively with all subdirectories and files"},
			"a":         {Short: "-a", Long: "--archive", Description: "Archive mode: preserve all attributes, timestamps, ownership, and recurse"},
			"archive":   {Short: "-a", Long: "--archive", Description: "Archive mode: preserve all attributes, timestamps, ownership, and recurse"},
			"u":         {Short: "-u", Long: "--update", Description: "Copy only when the source file is newer than the destination or destination is missing"},
			"v":         {Short: "-v", Long: "--verbose", Description: "Display the names of files as they are copied"},
			"i":         {Short: "-i", Long: "--interactive", Description: "Prompt before overwriting an existing destination file", Risk: RiskSafe},
			"f":         {Short: "-f", Long: "--force", Description: "Force copy: remove existing destination files if they cannot be opened", Risk: RiskMedium},
			"p":         {Short: "-p", Long: "--preserve", Description: "Preserve file mode, ownership, and timestamps"},
			"s":         {Short: "-s", Long: "--symbolic-link", Description: "Make symbolic links instead of copying file data"},
		},
	},

	"mv": {
		Name:        "mv",
		Category:    "FileOps",
		Summary:     "Moves or renames files and directories",
		Description: "Relocates files/directories to a new path or renames them.",
		DefaultRisk: RiskMedium,
		Flags: map[string]FlagDef{
			"f":           {Short: "-f", Long: "--force", Description: "Overwrite existing destination files without prompting", Risk: RiskHigh},
			"force":       {Short: "-f", Long: "--force", Description: "Overwrite existing destination files without prompting", Risk: RiskHigh},
			"i":           {Short: "-i", Long: "--interactive", Description: "Prompt before overwriting an existing destination file", Risk: RiskSafe},
			"interactive": {Short: "-i", Long: "--interactive", Description: "Prompt before overwriting an existing destination file", Risk: RiskSafe},
			"n":           {Short: "-n", Long: "--no-clobber", Description: "Do not overwrite an existing destination file", Risk: RiskSafe},
			"u":           {Short: "-u", Long: "--update", Description: "Move only when source is newer than destination or destination is missing"},
			"v":           {Short: "-v", Long: "--verbose", Description: "Explain what is being moved or renamed"},
		},
	},

	"ls": {
		Name:        "ls",
		Category:    "FileOps",
		Summary:     "Lists directory contents, files, and attributes",
		Description: "Displays information about files and directories in the filesystem.",
		DefaultRisk: RiskSafe,
		Flags: map[string]FlagDef{
			"l":     {Short: "-l", Description: "Use a long listing format (shows permissions, owner, size, modification date)"},
			"a":     {Short: "-a", Long: "--all", Description: "Show all files including hidden files (those starting with .)"},
			"all":   {Short: "-a", Long: "--all", Description: "Show all files including hidden files (those starting with .)"},
			"A":     {Short: "-A", Long: "--almost-all", Description: "Show all files including hidden ones, but exclude implied '.' and '..'"},
			"h":     {Short: "-h", Long: "--human-readable", Description: "Print human-readable file sizes (e.g., 1K, 234M, 2G)"},
			"t":     {Short: "-t", Description: "Sort files by modification time, newest first"},
			"r":     {Short: "-r", Long: "--reverse", Description: "Reverse the sort order"},
			"R":     {Short: "-R", Long: "--recursive", Description: "Recursively list all subdirectories"},
			"S":     {Short: "-S", Description: "Sort files by file size, largest first"},
			"1":     {Short: "-1", Description: "List one file per line"},
			"d":     {Short: "-d", Long: "--directory", Description: "List directories themselves, not their contents"},
			"color": {Long: "--color", Description: "Colorize the output to distinguish file types"},
		},
	},

	"mkdir": {
		Name:        "mkdir",
		Category:    "FileOps",
		Summary:     "Creates one or more new directories",
		Description: "Creates directories with the specified names.",
		DefaultRisk: RiskLow,
		Flags: map[string]FlagDef{
			"p":       {Short: "-p", Long: "--parents", Description: "Create parent directories as needed without throwing an error if they exist"},
			"parents": {Short: "-p", Long: "--parents", Description: "Create parent directories as needed without throwing an error if they exist"},
			"v":       {Short: "-v", Long: "--verbose", Description: "Print a message for each created directory"},
			"m":       {Short: "-m", Long: "--mode", TakesValue: true, ValueName: "MODE", Description: "Set file permission mode (as in chmod) for new directories"},
		},
	},

	"chmod": {
		Name:        "chmod",
		Category:    "FileOps",
		Summary:     "Changes file access permissions (read, write, execute)",
		Description: "Modifies read (r), write (w), and execute (x) permissions for owner, group, and others.",
		DefaultRisk: RiskMedium,
		Flags: map[string]FlagDef{
			"R":         {Short: "-R", Long: "--recursive", Description: "Change permissions of files and directories recursively", Risk: RiskHigh},
			"recursive": {Short: "-R", Long: "--recursive", Description: "Change permissions of files and directories recursively", Risk: RiskHigh},
			"v":         {Short: "-v", Long: "--verbose", Description: "Output a diagnostic for every file processed"},
			"c":         {Short: "-c", Long: "--changes", Description: "Like verbose, but report only when a change is actually made"},
		},
	},

	"chown": {
		Name:        "chown",
		Category:    "FileOps",
		Summary:     "Changes file owner and group",
		Description: "Modifies user ownership and group ownership of files and directories.",
		DefaultRisk: RiskMedium,
		Flags: map[string]FlagDef{
			"R":         {Short: "-R", Long: "--recursive", Description: "Operate on files and directories recursively", Risk: RiskHigh},
			"recursive": {Short: "-R", Long: "--recursive", Description: "Operate on files and directories recursively", Risk: RiskHigh},
			"v":         {Short: "-v", Long: "--verbose", Description: "Output a diagnostic for every file processed"},
			"c":         {Short: "-c", Long: "--changes", Description: "Report only when a change is made"},
		},
	},

	"find": {
		Name:        "find",
		Category:    "Search",
		Summary:     "Searches for files and directories in a directory hierarchy",
		Description: "Real-time search tool that evaluates conditions (name, type, size, modification time) across the filesystem.",
		DefaultRisk: RiskSafe,
		Flags: map[string]FlagDef{
			"name":      {Long: "-name", TakesValue: true, ValueName: "PATTERN", Description: "Match file/folder names case-sensitively using shell wildcard pattern"},
			"iname":     {Long: "-iname", TakesValue: true, ValueName: "PATTERN", Description: "Match file/folder names case-insensitively"},
			"type":      {Long: "-type", TakesValue: true, ValueName: "c", Description: "Filter by type: 'f' (file), 'd' (directory), 'l' (symlink)"},
			"size":      {Long: "-size", TakesValue: true, ValueName: "N", Description: "Filter by file size (e.g. +100M for >100MB, -1k for <1KB)"},
			"mtime":     {Long: "-mtime", TakesValue: true, ValueName: "N", Description: "Filter by file modification time in days (e.g. -7 for last 7 days, +30 for older than 30 days)"},
			"maxdepth":  {Long: "-maxdepth", TakesValue: true, ValueName: "N", Description: "Descend at most N directory levels"},
			"mindepth":  {Long: "-mindepth", TakesValue: true, ValueName: "N", Description: "Do not apply tests at levels less than N"},
			"exec":      {Long: "-exec", TakesValue: true, ValueName: "CMD ... {}", Description: "Execute command on each matched file", Risk: RiskHigh},
			"delete":    {Long: "-delete", Description: "Delete matched files directly (DANGEROUS: check search results first!)", Risk: RiskCritical},
			"empty":     {Long: "-empty", Description: "Match empty files or empty directories"},
			"print":     {Long: "-print", Description: "Print full file name on stdout followed by newline (default behavior)"},
		},
	},

	"grep": {
		Name:        "grep",
		Category:    "Search",
		Summary:     "Searches for patterns and regular expressions in files or input streams",
		Description: "Scans input line by line and prints lines matching the specified pattern.",
		DefaultRisk: RiskSafe,
		Flags: map[string]FlagDef{
			"i":         {Short: "-i", Long: "--ignore-case", Description: "Ignore case distinctions in patterns and input data"},
			"v":         {Short: "-v", Long: "--invert-match", Description: "Invert match: select non-matching lines"},
			"r":         {Short: "-r", Long: "--recursive", Description: "Read all files under each directory recursively"},
			"R":         {Short: "-R", Long: "--dereference-recursive", Description: "Recursively read files following all symbolic links"},
			"n":         {Short: "-n", Long: "--line-number", Description: "Prefix each output line with its 1-based line number"},
			"c":         {Short: "-c", Long: "--count", Description: "Print only a count of matching lines per file"},
			"l":         {Short: "-l", Long: "--files-with-matches", Description: "Print only names of files with matching lines"},
			"L":         {Short: "-L", Long: "--files-without-match", Description: "Print only names of files containing no match"},
			"w":         {Short: "-w", Long: "--word-regexp", Description: "Match only whole words"},
			"E":         {Short: "-E", Long: "--extended-regexp", Description: "Interpret pattern as an Extended Regular Expression (ERE)"},
			"F":         {Short: "-F", Long: "--fixed-strings", Description: "Interpret pattern as fixed strings, not regular expressions"},
			"o":         {Short: "-o", Long: "--only-matching", Description: "Print only the matched parts of a line"},
			"A":         {Short: "-A", TakesValue: true, ValueName: "NUM", Description: "Print NUM lines of trailing context after matching lines"},
			"B":         {Short: "-B", TakesValue: true, ValueName: "NUM", Description: "Print NUM lines of leading context before matching lines"},
			"C":         {Short: "-C", TakesValue: true, ValueName: "NUM", Description: "Print NUM lines of output context around matching lines"},
			"color":     {Long: "--color", Description: "Surround the matched strings with colored escape sequences"},
		},
	},

	"rsync": {
		Name:        "rsync",
		Category:    "Network",
		Summary:     "Fast, versatile file-copying and synchronization tool",
		Description: "Synchronizes files locally or over SSH using delta-transfer algorithm to transfer only changed blocks.",
		DefaultRisk: RiskMedium,
		Flags: map[string]FlagDef{
			"a":         {Short: "-a", Long: "--archive", Description: "Archive mode: preserves permissions, symlinks, timestamps, owner, group and recurses"},
			"v":         {Short: "-v", Long: "--verbose", Description: "Increase verbosity (display transferred file names)"},
			"z":         {Short: "-z", Long: "--compress", Description: "Compress file data during transfer to save bandwidth"},
			"P":         {Short: "-P", Description: "Equivalent to --partial --progress (shows progress bar & keeps partial transfers)"},
			"progress":  {Long: "--progress", Description: "Show progress during transfer"},
			"delete":    {Long: "--delete", Description: "Delete extraneous files from destination directory that are not in source (DANGEROUS)", Risk: RiskCritical},
			"e":         {Short: "-e", TakesValue: true, ValueName: "COMMAND", Description: "Specify remote shell to use (e.g. -e 'ssh -p 2222')"},
			"r":         {Short: "-r", Long: "--recursive", Description: "Recurse into directories"},
			"u":         {Short: "-u", Long: "--update", Description: "Skip files that are newer on the receiver side"},
			"n":         {Short: "-n", Long: "--dry-run", Description: "Perform a trial run with no changes made (Safe preview)", Risk: RiskSafe},
			"exclude":   {Long: "--exclude", TakesValue: true, ValueName: "PATTERN", Description: "Exclude files matching pattern"},
		},
	},

	"curl": {
		Name:        "curl",
		Category:    "Network",
		Summary:     "Transfers data to or from a server using protocols (HTTP, HTTPS, FTP, etc.)",
		Description: "Command-line tool for fetching URLs, testing APIs, and downloading web content.",
		DefaultRisk: RiskLow,
		Flags: map[string]FlagDef{
			"s":         {Short: "-s", Long: "--silent", Description: "Silent mode: do not show progress meter or error messages"},
			"S":         {Short: "-S", Long: "--show-error", Description: "When used with -s, show error message if it fails"},
			"L":         {Short: "-L", Long: "--location", Description: "Follow HTTP redirects (301, 302)"},
			"O":         {Short: "-O", Long: "--remote-name", Description: "Write output to a local file named like the remote file"},
			"o":         {Short: "-o", Long: "--output", TakesValue: true, ValueName: "FILE", Description: "Write output to specified file instead of stdout"},
			"I":         {Short: "-I", Long: "--head", Description: "Fetch HTTP headers only"},
			"X":         {Short: "-X", Long: "--request", TakesValue: true, ValueName: "METHOD", Description: "Specify custom HTTP request method (e.g. GET, POST, PUT, DELETE)"},
			"d":         {Short: "-d", Long: "--data", TakesValue: true, ValueName: "DATA", Description: "Send HTTP POST data (application/x-www-form-urlencoded)"},
			"H":         {Short: "-H", Long: "--header", TakesValue: true, ValueName: "HEADER", Description: "Pass custom HTTP header to server (e.g. 'Authorization: Bearer ...')"},
			"k":         {Short: "-k", Long: "--insecure", Description: "Allow insecure server connections (skip SSL/TLS certificate verification)", Risk: RiskMedium},
			"u":         {Short: "-u", Long: "--user", TakesValue: true, ValueName: "USER:PASS", Description: "Specify user and password for server authentication"},
			"f":         {Short: "-f", Long: "--fail", Description: "Fail silently on HTTP errors (return exit code > 0 on 4xx/5xx)"},
			"v":         {Short: "-v", Long: "--verbose", Description: "Make curl verbose (shows request/response headers and handshake)"},
		},
	},

	"ps": {
		Name:        "ps",
		Category:    "Process",
		Summary:     "Reports a snapshot of the current running processes",
		Description: "Displays active system processes, process IDs (PID), memory/CPU usage, and terminal states.",
		DefaultRisk: RiskSafe,
		Flags: map[string]FlagDef{
			"aux":   {Short: "aux", Description: "Show all processes for all users in full BSD-style listing format"},
			"ef":    {Short: "-ef", Description: "Show all processes on system with full standard listing format"},
			"e":     {Short: "-e", Description: "Select all processes"},
			"f":     {Short: "-f", Description: "Do full-format listing (UID, PID, PPID, C, STIME, TTY, TIME, CMD)"},
			"u":     {Short: "-u", TakesValue: true, ValueName: "USER", Description: "Filter processes by effective user name or ID"},
			"p":     {Short: "-p", TakesValue: true, ValueName: "PID", Description: "Select by process ID"},
		},
	},

	"kill": {
		Name:        "kill",
		Category:    "Process",
		Summary:     "Sends a signal to terminate or control processes",
		Description: "Sends specified POSIX signals (default: SIGTERM 15) to target process IDs.",
		DefaultRisk: RiskHigh,
		Flags: map[string]FlagDef{
			"9":     {Short: "-9", Long: "-SIGKILL", Description: "Force kill immediately (uninterceptable kill signal)", Risk: RiskCritical},
			"15":    {Short: "-15", Long: "-SIGTERM", Description: "Graceful termination request (allows process to clean up)"},
			"1":     {Short: "-1", Long: "-SIGHUP", Description: "Hangup signal: often reloads configuration files in daemons"},
			"l":     {Short: "-l", Description: "List all available signal names and numbers"},
		},
	},

	"dd": {
		Name:        "dd",
		Category:    "System",
		Summary:     "Converts and copies raw data, files, and disk partitions",
		Description: "Low-level byte stream copier commonly used for writing ISO images or cloning disks. High potential for accidental data destruction.",
		DefaultRisk: RiskCritical,
		Flags: map[string]FlagDef{
			"if":     {Long: "if=", TakesValue: true, ValueName: "FILE", Description: "Input file or device path to read from"},
			"of":     {Long: "of=", TakesValue: true, ValueName: "FILE", Description: "Output file or device path to write to (OVERWRITES DESTINATION)", Risk: RiskCritical},
			"bs":     {Long: "bs=", TakesValue: true, ValueName: "BYTES", Description: "Read and write up to BYTES at a time (e.g. 4M, 1M, 512)"},
			"count":  {Long: "count=", TakesValue: true, ValueName: "N", Description: "Copy only N input blocks"},
			"status": {Long: "status=", TakesValue: true, ValueName: "LEVEL", Description: "Level of information to print (e.g. status=progress shows real-time transfer speed)"},
		},
	},
}
