name: Run Tests


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] # هتشتغل مع أي PR رايح لفرع الـ main

jobs:
  test:

    runs-on: ubuntu-latest 

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4

   
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.27' 

  
    - name: Install dependencies
      run: go mod download


    - name: Run unit tests
      run: go test -v ./...